LEXICON_RU = {'/start': 'START DESC\n\nYou are not registered! Use /register to register',
              '/start_registered': 'You are already registered! Use /menu command',
              'error_cancel_on_registration_default': 'CANCEL ON REGISTRATION WITH DEFAULT STATE',
              'error_cancel_on_registration': 'CANCEL ON REGISTRATION',
              'registrate_start': 'START REGISTRATION\n\nEnter room number',
              'registrate_room_accept': 'ACCEPTED ROOM',
              'error_room_input': 'INVALID ROOM NUMBER',
              'main_menu_message': 'Main menu message',
              'to_use_menu': 'Use /menu',
              'loading_shops_1': 'Loading list of shops...',

              'loading_shops_2': 'Baking pies...',
              'loading_shops_3': 'Cooking some pasta...',
              'loading_shops_4': 'Do some hiking...',
              'loading_shops_5': 'Laying on a sofa...',
              
              'error_pagination': 'Pagination error!',

              'USER_INFO': '<b>Информация о пользователе:\n\nTelegram ID: {tg_id}\nИмя: {full_name}\nКомната проживания: {room}\nСтатус продавца: {is_seller}\n\
Количество заказов: {orders_count}</b>',
              'SHOP_INFO': '<b>Магазин "{name}"\n\nОписание:\n{description}\n\nСтатус: {is_active}\nКонтакт для связи: {admin_id}</b>',
              'CHOOSE_PRODUCT': 'Choose product!',
              'PRODUCT_CARD': '<b>{name}\n\nОписание: {description}\nЦена: {price}</b>',
              'START_ORDER': 'Start order message. Confirm data?\n\nUsername ID: {username}\nRoom: {room}\nProduct: {product_name}\nPrice: {price}',
              'ORDER_ACCEPTED': 'Order successfully accepted! Check your orders in "My orders" in main menu!',
              'ORDER_DECLINED': 'You declined your order! Wish you will find a nice one',
              'ALREADY_REGISTERED': 'You are already registered! Use /menu command',
              'MY_SHOP_MESSAGE': "Welcome to control panel of your shop",
              'ERROR_MYSHOP_COMMAND': 'You are not the seller!',
              'CURRENT_SHOP_INFO_MESSAGE': '<b>INFORMATION ABOUT SHOP\n\nName: {name}\nDesc: {description}\nStatus: {is_active}\nAdmin: {admin_id}</b>',
              'CHANGE_SHOP_INFO': 'Changing shop info message',
              'INPUT_NEW_SHOP_NAME': 'Enter new shop name\n/cancel_edit to cancel operation',
              'SUCCESSFUL_CHANGING_SHOP_NAME': 'Вы успешно изменили имя магазина!',
              'INPUT_NEW_SHOP_DESC': 'Send new description',
              'SUCCESSFUL_CHANGING_SHOP_DESC': 'Successful changed shop description',
              'INPUT_NEW_SHOP_PHOTO': 'Send new photo for shop',
              'SUCCESSFUL_CHANGING_SHOP_PHOTO': 'Successful changed shop photo',
              'STATUS_CHANGED_SUCCESSFULLY': 'Status changed successfully\nType /myshop to update status button',
              'EDIT_PRODUCT_MESSAGE': 'Edit products list menu',
              'EDIT_PRODUCT_CARD': 'Product: \n{name}\nDescription:\n{description}\nPrice:\n{price}',
              'NEW_PRODUCT_NAME': 'Send new product name\n/cancel_edit_product to cancel editing',
              'NEW_PRODUCT_DESCRIPTION': 'Send new product description',
              'NEW_PRODUCT_PRICE': 'Send new product price',
              'SUCCESSFULL_CHANGE_PRODUCT': 'Successfull changing product',
              'CANCEL_EDIT_PRODUCT': 'Canceled editing product!',
              'DELETING_PRODUCT_CARD_CONFIRMATION_MESSAGE': 'Confirmation to remove product card',
              'DECLINED_DELETE_PRODUCT_CARD_ALERT': 'Declined deleting product card!',
              'CONFIRM_DELETING_PRODUCT_CARD_WITH_PRICE_MESSAGE': 'Type {price} (product price) to confirm deleting product card',
              'SUCCESSFULL_DELETE_PRODUCT_CARD': 'Успешное удаление карточки товара!',
              'WRONG_CONFIRMATION_PRICE': 'Неверно указанная цена товара! Удаление отменено',
              'SHOP_STATISTICS_MESSAGE': 'Shop {name}\nTotal orders: {total_count}\nTotal sum: {total_sum}',
              'SHOP_ORDERS_MESSAGE': "Here's your orders!"
              }

LEXICON_RU_BUTTONS = {
    'STATS_BUTTON': 'Stats',
    'BOT_INFO_BUTTON': 'Bot info button [X]',
    'CHECK_SHOPS': 'To list of shops',
    'MY_ORDERS': 'To find something [X]',
    'CANCEL': 'cancel button',
    "VISIT_SHOP": "Visit current shop",
    'CANCEL_TO_PRODUCT_LIST': 'cancel to product_list',
    'ORDER_PRODUCT': 'Order a product button',
    'CONFIRM_ORDER': 'Confirm order button',
    'DECLINE_ORDER': 'Decline order button',
    '->': '->',
    '<-': '<-',
    'LEAVE_PRODUCTS_LIST_BUTTON': 'Cancel',
    'EDIT_SHOP_INFO': 'Edit shop inf',
    'EDIT_SHOP_STATUS_ACTIVE': 'Статус: +',
    'EDIT_SHOP_STATUS_INACTIVE': 'Статус: -',
    'CHECK_SHOP_STATS': 'Check shop"s statistics',
    'EDIT_PRODUCTS_LIST': "Edit products list",
    'CHECK_SHOP_ORDERS': 'Check my orders',
    'EDIT': 'Edit',
    'EDIT_SHOP_INFO:NAME': 'Edit name',
    'EDIT_SHOP_INFO:DESCRIPTION': 'Edit description',
    'EDIT_SHOP_INFO:STATUS': 'Edit status',
    'EDIT_SHOP_INFO:PHOTO': 'Edit photo',
    'EDIT_PRODUCT': "Edit current product",
    'DELETE_PRODUCT': 'Delete current product',
    'CONFIRM_DELETE_PRODUCT_CARD': 'Confirm',
    'DECLINE_DELETE_PRODUCT_CARD': 'Decline',
    'ACTIVE_ORDER_SELLER_MENU': 'Order {order_id}'
}